## Lektüre & Quiz: `S3` 

Lesen Sie das [`S3`](https://adv-r.hadley.nz/s3.html) Kapitel von H. Wickham's *Advanced R*. 
Bearbeiten Sie (mindestens) die folgenden von dort übernommenen/inspirierten Aufgaben:

- Was tut die `as.data.frame.data.frame()` Methode? 
Der obige Befehl setzt sich ja auch aus einem <generic>.<class> zusammen, wobei die <generic> `as.data.frame` ist und die <class> `data.frame` ist. Wenn man die `?as.data.frame` anschaut wird diese auch nicht als Moeglichkeit genannt. Jetzt zudem was sie tut. Hat ein Objekt neben der data.frame weitere Klassen z.b. `class(test) <- c("super.sick.data.frame", "data.frame")` werden alle Klassen ausser der "data.frame"-Klasse entfernt.
Warum ist das verwirrend?
Das <.data.frame> impliziert ja bereits die Klasse. Wir wissen bereits, dass es ein data.frame ist und speichern ihn erneut als data.frame aber nehmen ihm die restlichen Klassen weg. Ausserdem sind doch ein paar viele Punkte enthalten. Eigentlich sollte nur ein Punkt, wie oben gezeigt, enthalten sein.
Wie können Sie derartige Verwirrung in Ihrem eigenen Code vermeiden?
as_dataframe() statt as.data.frame().
Aehnlich wie bei dplyr. Hier wurde as.tbl durch as_tibble ersetzt.


- Beschreiben/erklären Sie das Verhalten dieses Codes:
```r
set.seed(1014)
some_days <- as.Date("2019-11-24") + sample(10, 5)
mean(some_days)
# [1] "2019-11-30"
mean(unclass(some_days))
# [1] 18230.4
```
Wenn some_days die Klasse genommen wird, handelt es sich hier nur noch um die Klasse numeric. Genauer gesagt handelt es sich hier aber dann um die Anzahl der verstrichen Tage seit 01.01.1970 (origin used by R). (`as.Date("1970-01-01")+18230.4 == mean(some_days)`) Aber irgendwie finde ich `as.Date("1970-01-01")+18230.4` etwas gefaehrlich, da auf ein Datum eine Zahl addiert wird. `+` musst also wissen wie es damit umgehen muss.
`mean(some_days)` macht im Prinzip das gleiche wie `as.Date("1970-01-01")+mean(unclass(some_days))` nur besser da hier einem "klassenlosen" Objekt  durch `.Date(mean(unclass(some_days)))` wieder eine Klasse ("Date") zugeordnet wird. Sozusagen ist `mean(unclass(some_days))` ein Teilschritt in `mean(some_days)`.

- Welche Klasse hat `x` im folgenden Code? Auf welchem *base type* basiert diese Klasse? Welche Attribute nutzt sie und wie sind die mathematischen Eigenschaften von Verteilungsfunktionen hier konkret implementiert? 
```r
x <- ecdf(rpois(100, 10))
x
# Empirical CDF 
# Call: ecdf(rpois(100, 10))
#  x[1:15] =      1,      4,      5,  ...,     16,     17
```
- Schreiben Sie einen neuen low-level Konstruktor für `data.frame`-Objekte (ohne die Funktionen `as.data.frame()` oder `data.frame()` zu benutzen, selbstverständlich). Machen Sie sich zunächst klar: Auf welchem *base type* basiert `data.frame`? Welche Attribute nutzt `data.frame`? Welche Restriktionen gelten für die verschiedenen Einträge und Attribute?  
    *Hinweis*: Sehen Sie sich dafür zunächst mal so etwas wie `str(unclass(<irgend ein data.frame>))` an.
- Kategorisieren Sie die Klassen der Rückgabe-Objekte von `lm(), factor(), table(), as.Date(), as.POSIXct(), ecdf(), ordered(), I()` in die Klassentypen *vector class*, *record style class*, *scalar class* die in *Advanced R* beschrieben  werden.
- Wie sähe ein Konstruktor `new_lm` für Objekte der Klasse `lm` aus? Warum wäre ein solcher Konstruktor vermutlich nicht besonders nützlich? 
- Lesen Sie den Quellcode für `t()` und `t.test()`. Ist `t.test()` eine generische S3 Funktion oder eine S3 Methode? Was passiert **im Detail** wenn sie `t()` auf ein S3-Objekt mit Klasse `test` anwenden (s.u.)? Warum?
```r
x <- structure(1:10, class = "test")
t(x)
```

